language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - git submodule update --init --recursive
install:
  # Moon
  - sudo apt-get install -qq libopenal-dev libdevil-dev libglfw-dev libglew-dev freeglut3-dev libx11-dev libxmu-dev libxi-dev libyaml-dev
  # GLFW3
  - sudo apt-get install -qq xorg-dev libglu1-mesa-dev
script:
  - bash build.sh
