language: cpp
compiler:
 - gcc
 - clang
before_install:
 - pwd
 - git submodule update --init --recursive
 - sudo apt-get update -qq
 - sudo apt-get install -qq libopenal-dev libdevil-dev libglfw-dev

before_script:
 - cd -
 - mkdir build
 - cd build
 - cmake ..
script:
 - make -j4
