language: cpp
sudo: false
addons:
  apt:
    sources:
    - kalakris-cmake
    packages:
    - libopenal-dev
    - libdevil-dev
    - libglew-dev
    - libgles2-mesa-dev
    - freeglut3-dev
    - libx11-dev
    - libxmu-dev
    - libxi-dev
    - libyaml-dev
    - xorg-dev
    - libglu1-mesa-dev
    - cmake
matrix:
  include:
    - compiler: gcc
      env: MOON_MRUBY_TOOLCHAIN=gcc

    - compiler: clang
      env: MOON_MRUBY_TOOLCHAIN=clang

  allow_failures:
    - compiler: clang

before_install:
  - git submodule update --init --recursive --depth=1
  # build.cmake-data
  #- wget http://ftp.us.debian.org/debian/pool/main/c/cmake/cmake-data_2.8.9-1_all.deb
  #- dpkg -i --force-not-root --root=$HOME ./cmake-data_2.8.9-1_all.deb
  #- rm -v ./cmake-data_2.8.9-1_all.deb
  # build.cmake
  #- wget http://ftp.us.debian.org/debian/pool/main/c/cmake/cmake_2.8.9-1_amd64.deb
  #- dpkg -i --force-not-root --root=$HOME ./cmake_2.8.9-1_amd64.deb
  #- rm -v ./cmake_2.8.9-1_amd64.deb

install:
  # ruby bundler
  - ruby --version
  - gem install bundler
  - bundle install

before_script:
  - cmake --version
  - ruby --version

script:
  - bundle exec rake --verbose build
  - ruby travis/check_libs.rb
